# Generated by Django 4.0.1 on 2022-01-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circulares_Despachadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_circ', models.CharField(max_length=10, verbose_name='No. Circular')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dirigido', models.TextField(max_length=500, verbose_name='Dirigido')),
                ('resumen', models.TextField(max_length=500, verbose_name='Resumen')),
                ('fecha_recibido', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(max_length=500, verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Circular Despachado',
                'verbose_name_plural': 'Circularer Despachados',
                'db_table': 'circ_desp',
            },
        ),
    ]
